### ISSUE TITLE
Error:   make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by keegit** [dss-extensions/klusolve#17]
I am building `klusolve` using the `cmake` Rust crate from within a cargo build script. I only encounter this error If I set `USE_SYSTEM_SUITESPARSE=ON`. I can't seem to find the `cmake` command ran anywhere in the `klusolve` source.

```
  running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--parallel" "8"

  --- stderr
  make: warning: -j8 forced in submake: resetting jobserver mode.
  make: *** No rule to make target 'install'.  Stop.
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2
```

**Comment by PMeira** [comment]
> USE_SYSTEM_SUITESPARSE=ON

Do you have the dev/devel packages installed for SuiteSparse?

Which distribution is this? Assuming this is Linux, since `USE_SYSTEM_SUITESPARSE=ON` may not be of much use otherwise.

You can see how the binary package was built from https://github.com/dss-extensions/klusolve/blob/master/.travis.yml and https://github.com/dss-extensions/klusolve/blob/master/ci/build_linux_x64.sh

(The Travis-CI build is disabled nowadays, we will migrate to GitHub Actions sooner or later)

The image  `manylinux_wheel_cmake_fpc320` is only used to ensure compatibility across multiple systems. You can can build with your local system tools.

**Comment by keegit** [comment]
Yeah I have the development packages installed, assuming this is what you mean `libsuitesparse-dev`. I do build with my local system tools which is why I'm unsure what the source of error could be.

**Comment by PMeira** [comment]
Inspect the files generated by CMake, e.g. `CMakeOutput.log` and `CMakeCache.txt`.

There's nothing that special for this build. If CMake did find the headers and libs, the detailed cache should list them.

**Comment by keegit** [comment]
Closing - no solution found though.
